#!/bin/bash
sort /etc/passwd | cut -d':' -f 1,6 >> 22-users_and_homes
echo "sort /etc/passwd | cut -d: -f 1,6" >> 22-users_and_homes
echo "sort /etc/passwd | cut -d: -f 1,6"
sort /etc/passwd | cut -d ':' -f 1,6
